[package]
name = "warmup_rust_build_script"
version = "0.1.0"
authors = ["coder"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
